### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/CV#10]
Выложи плиз скриншоты с настройками которые ты использовала для PerfectPixel (в инверсии).

**Comment by kuvshinova-am** [comment]
подгоняла под настройки width: 1200px
![fireshot capture 2 - cv - http___localhost_9000_](https://user-images.githubusercontent.com/24365265/42935684-765237ac-8b74-11e8-9de6-2e999a6e5e35.png)

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/commit/1e734364d1c2e843e6f765d279bafae983b99a50

**Comment by ValentinAlexandrovich** [comment]
Подравняй переносы текста в блоках profile, education, experience, чтобы не было большого расхождения c макетом.  А в software увеличь толщину букв, и возможно расстояние между буквами. Выложишь сюда еще скриншот с измененениями и можешь закрывать.

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/commit/c9e615b461fad84b0d5318ae09907f535214d347
![fireshot capture 3 - cv - http___localhost_9000_](https://user-images.githubusercontent.com/24365265/42982754-07f7f488-8c0d-11e8-8100-9ac7b31a3cd3.png)
готово
