### ISSUE TITLE
Рефакторинг (пожелания)

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/CV#12]
Используй плиз для рефакторинга одну ветку, так не удобно отслеживать ветки. Сейчас к примеру можешь все влить в ветку в refactoring и использовать ее в дальнейшем для коммитов) Остальные ветки удали, кроме мастера) Также установи ветку  refactoring дэфолтной, чтобы не ненужно было переключаться каждый раз.

**Comment by kuvshinova-am** [comment]
сделано
