### ISSUE TITLE
Import 

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/CV#17]
У тебя сейчас в index.js импортятся все файлы, реализуй это автоматически, чтобы не приходилось обо всех помнить) Заодно уйдут import из style.styl.

**Comment by kuvshinova-am** [comment]
уже несколько часов пытаюсь сделать динамический импорт
`
function requireAll (requireContext) {
  return requireContext.keys().map(requireContext);
}

requireAll(require.context('./components/', true, /^\.\/.*\.styl$/));
requireAll(require.context('./', true, /^\.\/.*\.styl$/));
requireAll(require.context('./components/img/', true, /^\.\/.*\.(jpg|svg)$/));
requireAll(require.context('./favicons/', true, /^\.\/.*\.js$/));
`
но почему то стили блоков не подключаються, хотя по идеии должны. Может подскажите в чем может быть проблема ?

**Comment by ValentinAlexandrovich** [comment]
Могу, но тут нужно самой поковыряться и запустить, в этом суть рефакторинга)

**Comment by kuvshinova-am** [comment]
у меня не работает только первый реквест. 
благодаря второму аргументу он должен проверять вложенные папки в  components, но он этого не делает.
уже пробовола разные варианты записи пути.
./components/**/
./components/*/ 
и тоже самое с символами экранирования. но не один не работает.

**Comment by ValentinAlexandrovich** [comment]
Залей в репозторий, то что ты пытаешься реализовать, чтобы было понятно где не срабатывает.

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/tree/dynamic_import
На самом деле они подключаються, но отдельными файлами, и они инжектятся под titel в HTML. Предыдущий вариант не инжектился непосредственно в HTML.

**Comment by ValentinAlexandrovich** [comment]
Т.е. сейчас все прдключается? а почему ты решила что они инжектится под title, в сборке этого не видно

**Comment by ValentinAlexandrovich** [comment]
В сборке в html этого не видно.

**Comment by kuvshinova-am** [comment]
действительно, но когда запускаю через localhost то стили как раз инжектятся в html

**Comment by ValentinAlexandrovich** [comment]
)) ты долго сидела над этим ишью?

**Comment by ValentinAlexandrovich** [comment]
Все работает, нужно только допилить константы цветов в стилях (которые в ветке рефакторинг подтягиваются из главного styl, а тут желательно создать файл с константами и подгружать его в каждый файл styl, поскольку на страницу  эти файлы инжектятся отдельно и подтянуть им значения цветов неоткуда)

**Comment by kuvshinova-am** [comment]
да, около 5 часов суммарно

**Comment by kuvshinova-am** [comment]
ну наконец-то. я потратила около 5 часов что бы понять в чем было дело. СПАСИБО за помощь. 
теперь готово 
https://github.com/kuvshinova-am/CV/commit/304bf825be6da2cb7fdf81e49fcac529051c542a
еще будут замечания по этому проекту?

**Comment by ValentinAlexandrovich** [comment]
Да у парней еще есть, они напишут позже. Насчет дс сторе в ветке рефакторинга в папке src до сих пор остались. Пока что подравь еще в стайлах оступы между элементами, блоками и т.д. а еще двоеточия там тоже никчему)
