### ISSUE TITLE
переусложнена структура блока в pug  файлах.

### ISSUE THREAD

**Issue by Geksanit** [kuvshinova-am/CV#2]
1. Сложность в том что трудно читать структуру блока. Слишком много импортов. Слишком много вспомогательных блоков, которые больше подходят как элементы блока.
2. Каждый блок должен быть миксином в pug - в этом вся суть.
3. div(class="skills-container") - можно писать гораздо короче.
4. Захардкорженность (нет возможности менять контент). Что, если в скиллах придется закрасить другое количиство кружков, или добавить новый скилл ? Должна быть возможность менять это через аргументы миксинов в pug.

**Comment by kuvshinova-am** [comment]
> div(class="skills-container") - можно писать гораздо короче.
так?  .skills-container
приму к сведению на будущее. в этом проекте оставлю так.
С остальными пунктами я пологаю я уже разобралась в первом ишью

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/commit/c99171aaba5e240a6f1876c1a72cb604fe58dcdb
готово
