### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by Geksanit** [kuvshinova-am/CV#20]
Скрипты должны запускать локальные модули. Сейчас только линт так запускается.
Раздели зависимости на dependencies и devDependencies.

**Comment by kuvshinova-am** [comment]
готово
https://github.com/kuvshinova-am/CV/commit/be1588f4795512408177a3e46c02aba33fe79b89

**Comment by Geksanit** [comment]
а dependencies и devDependencies ?

**Comment by Geksanit** [comment]
нет не всё в порядке,  в чем разница между devDependencies и dependencies ?

**Comment by kuvshinova-am** [comment]
dependencies - глобальные
devDependencies - локальные

**Comment by chmnkh** [comment]
Ты хочешь сказать, что пакеты из devDependencies устанавливаются локально, а dependencies - глобально?

**Comment by kuvshinova-am** [comment]
пакеты которые мы устанавливаем глобально попадают в dependencies https://webpack.js.org/guides/installation/#global-installation, а те что устанавливаються локально попадают в devDependencies. https://webpack.js.org/guides/installation/#local-installation

**Comment by chmnkh** [comment]
https://docs.npmjs.com/getting-started/using-a-package.json#specifying-dependencies
Отсюда вниз прочитай)

**Comment by kuvshinova-am** [comment]
ок, т.е. мне нужно в dependencies переместить некоторые зависимости. 
Эти: css-loader, file-loader, webpack?

**Comment by chmnkh** [comment]
Ну ты же поняла в чем разница между дев и не дев зависимостями?
Вот исходя из этого, ты должна два множества этих зависимостей определить.
Отвечая на твой вопрос: любые лоадеры и вебпак это точно не dependencies. Кстати, почему?)

**Comment by kuvshinova-am** [comment]
ну тогда я вижу только одну dependencies зависимость - npm, 
по поводу лоадеров, возможно потому что они служат для "поиска" файлов при разработке, и "транспортировки" их же на нужное место.

**Comment by chmnkh** [comment]
Про то, для чего лоадеры служат не совсем корректно.
Хорошо, такие вопросы: почему все кроме npm - devDependencies? Зачем тебе вообще пакет npm в зависимостях?

**Comment by kuvshinova-am** [comment]
все что связанно с вебпаком и все лоадера должны быть в devDependencies, pug и stylus нужны только при разработки, потому что эти файлы конвертируються в html и css соответсвенно. 
nod-static поидеи можно убрать, я перестала им пользоваться, но он так же нужен был исключительно для разработки. eslint проверяет на кодстаил - тоже разработка.  npm тоже можно убрать и без него работает. Он все еще тут т.к. по какомо ту гайду делала, и он устанавливался. По такой логиге у меня все правильно за исключением двух лишних зависимостей. и в dependencies быть не чего не должно.

**Comment by chmnkh** [comment]
Да, теперь все верно. 
Неиспользуемые пакеты тоже выпиливай, чтоб не смущали.

**Comment by Geksanit** [comment]
@chmnkh не прав. dependencies - это все зависимости необходимые для сборки. 
devDependencies - это всё остальное , необходимые для разработки (например eslint, webpack-dev-server).
Нужно это разделение что-бы на продакшн сервере устанавливать dependencies. А для разработки устанавливают dependencies + devDependencies.

**Comment by kuvshinova-am** [comment]
по такой логике в devDependencies останеться только  eslint, webpack-dev-server, а все остальное уйдет в dependencies, потому что все это нужно для сборки.

**Comment by Geksanit** [comment]
да

**Comment by kuvshinova-am** [comment]
готово
https://github.com/kuvshinova-am/CV/commit/261218b859e8d43420edca207b4ddf9031f7b7a5
