### ISSUE TITLE
linebreak-style

### ISSUE THREAD

**Issue by Geksanit** [kuvshinova-am/CV#21]
Весь проект перевести на unix-style line break symbols

**Comment by kuvshinova-am** [comment]
прокоментируйте пожалуйста, что вы имеете ввиду?

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/commit/a65a19b6d7f4ccaac74a8f3ff3e1ff2d30fd181f
надеюсь это то что требовалось

**Comment by Znack** [comment]
Судя по коммиту должно быть то, @Geksanit подтверди плиз

**Comment by Geksanit** [comment]
Подтверждаю 
![image](https://user-images.githubusercontent.com/31949379/43076232-bc554ed8-8ead-11e8-8a7f-951966662ecf.png)
