### ISSUE TITLE
Использовать деструктуризацию объектов

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/CV#25]
```
mixin person(options)
    - name = options.name || 'name'
    - surname = options.surname || 'surname'
    - job = options.job || 'job'
```
Вместо подобных штук лучше использовать деструктуризацию и параметры по умолчанию :)

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/commits/master
готово

**Comment by kuvshinova-am** [comment]
в header, list-item, person, profile
в первых двух вроде бы самый просто вариант

**Comment by kuvshinova-am** [comment]
заметила что ссылка корявая вверху 
https://github.com/kuvshinova-am/CV/commit/385b0c61778c0056e735089659ae912c0c117233

**Comment by chmnkh** [comment]
Я скорее имел в виду, что ты можешь дефолтные параметры задать прямо при объявлении миксина (так же как и для любой функции в js'e). 
Плюс у тебя сейчас с дефолтными значениями небольшая каша в том плане, что где-то (list-item, например) у тебя есть дефолтное значение для options, но дефолтных значений для свойств options у тебя нету, а в person, например, - все наоборот. Причем делать дефолтные значения для каждого свойства options может и не везде иметь смысл. Разберись с этим, и сделай везде одинаково.

**Comment by kuvshinova-am** [comment]
т.е. мне сделать так? во всех файлах 
![screenshot from 2018-07-26 14-29-54](https://user-images.githubusercontent.com/24365265/43247959-7e1e2b00-90e0-11e8-8a34-d2eded6822f4.png)

**Comment by chmnkh** [comment]
Этот код можно ну более лучший вариант переписать. Прямо при объявлении миксина ты можешь деструктуризировать опции и указать параметры по умолчанию таким вот образом:
```
mixin person({ name = 'name', surname = 'surname', job = 'job' })
```
Это будет намного лаконичнее и тебе не нужна будет вот эта строчка:
```
let { name = ... } = options;
```
Далее, для указания дефолтного значения для всего объекта options, можно написать так:
```
mixin person({ name = 'name', surname = 'surname', job = 'job' } = defaultOptions)
```
и не нужна будет строчка с ифом.
В принципе, если ты хочешь прямо задать defaultOptions (а не просто оставить пустой объект по дефолту, чтобы не было ошибок при обращении типа undefined.name, если options не передали, например), лучше их хранить отдельно в каком-то файле с константами. 
Вообще, по-поводу дефолтных значений: тут надо смотреть вообще необходимы ли они. Например, для всего объекта options имеет смысл какой-то дефолтный объект задать, чтобы не было ошибок при обращении типа undefined.name, если options не передали (это то, что я выше писал). Для каждого из параметров, типа name или surname, может быть и не обязательно эти дефолты делать, у тебя ведь ничего не сломается, если ты их не передашь, да и вообще, может ли быть анкета с какими-то дефолтными именем и фамилией человека, это же немного странно? Короче, если ты делаешь дефолтное значение, думай о том, нужно ли оно и имеет ли оно смысл, а не просто так ставь его, чтобы оно было. Если ты где-то не задашь дефолтное значение - это может быть и норм.

**Comment by kuvshinova-am** [comment]
а как при такой записи передавать параметры в другой миксин?
например у меня все блоки передают массив options в миксин с заголовком, и он там парсится. 
Пробовала просто передать title, миксин в таком случаи использует дефолтное значение.

**Comment by kuvshinova-am** [comment]
уведомления о том что с сделала пулреквест приходят?

**Comment by chmnkh** [comment]
Чтобы я мог вмердживать, тебе нужно меня в коллабораторы добавить.
Добавь в коллабораторы (загуглить можно, как), а потом в Reviewers меня укажи. Для ишью, которые другие люди создавали то же самое сделать нужно будет.

**Comment by ValentinAlexandrovich** [comment]
По этому макету у меня больше не будет ишью, усложнение архитектуры не будет рациональным, этого уровня вполне достаточно.
