### ISSUE TITLE
Блок profile не по макету

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/CV#26]
![image](https://user-images.githubusercontent.com/18498637/43126951-6926b8c2-8f58-11e8-8644-149bccc8ffc2.png)
а где жирный текст?)

**Comment by kuvshinova-am** [comment]
готово
https://github.com/kuvshinova-am/CV/commit/8a61a2b57556fad499b59a4e6d15d5362215e662
![fireshot capture 6 - cv - http___localhost_9000_](https://user-images.githubusercontent.com/24365265/43202381-90dd0fcc-9045-11e8-9abf-50e1d2beaf4d.png)
p.s. у меня в текстовых блоках используеться другой текст, не тот что в макере, поэтому точное попадание не возможно.

**Comment by chmnkh** [comment]
У тебя сейчас параметр, отвечающий за жирный текст называется boldText. А если я как-то иначе захочу этот текст выделить, например подчеркнуть, или курсивом? Такие штуки нужно называть не по внешнему виду, а по смыслу.
Тут может быть такой момент, что не совсем понятно что именно этот жирный текст может означать, но здесь ты можешь сама придумать что-то, что может подойти, 100% правильного ответа нет.

**Comment by chmnkh** [comment]
Часть речи не модификаторная)

**Comment by kuvshinova-am** [comment]
accented подойдет?
