### ISSUE TITLE
Использовать семантические теги

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/CV#27]
Для много из того, что сейчас на дивах, можно найти более подходящие по семантике теги :)

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/commit/94445d995a2420f8301dd94236ba0757b024477f
готово

**Comment by ValentinAlexandrovich** [comment]
Посмотри вот здесь https://html5book.ru/html-tags/ возможно добавить в проект <figure> <main> <progress> <figcaption> возможно еще подойдут какие-нибудь)

**Comment by ValentinAlexandrovich** [comment]
Тэги  figure, progress, figcaption не применяй - они семантически не точно подходят к данному макету)

**Comment by kuvshinova-am** [comment]
фрррр я только закончила с ними. хотела комит делать.

**Comment by ValentinAlexandrovich** [comment]
Добавляй main и выкладывай)

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/commits/master
немного поторопилась и забыла проставить тег ишью

**Comment by kuvshinova-am** [comment]
что с этим ишью???

**Comment by chmnkh** [comment]
никто про ишью не забывает никакие, не надо напоминать плз)

**Comment by kuvshinova-am** [comment]
по этому ишью все сделанно

**Comment by kuvshinova-am** [comment]
и мне Сергей сказал напоминать, так что я напоминаю

**Comment by chmnkh** [comment]
Напоминать нужно, когда тебя какое-то время не смотрят вообще, например. Спрашивать по каждому ишью почему оно не закрыто, когда тебя полчаса назад смотрели - неправильно. Если ишью не закрыто - это же не просто так, наверняка какие-то причины есть.

**Comment by chmnkh** [comment]
Если ты будешь в каждом ишью писать "что с этим ишью", это проверку ну никак не ускорит)

**Comment by kuvshinova-am** [comment]
последний раз коментарий был от Валентина день назад, пологаю суток достаточно что бы проверить

**Comment by chmnkh** [comment]
А откуда ты знаешь, что достаточно? Откуда ты знаешь, чем сегодня люди занимались и сколько у них было времени, которое можно было бы выделить на ревью твоего задания?)

**Comment by chmnkh** [comment]
Если тебе кажется, что с тобой вдруг как-то несправедливо обходятся, ты можешь у Сергея спросить, как что происходит, если ты не веришь мне)

**Comment by kuvshinova-am** [comment]
если ишью накинул так будь добр хотя бы их проверяй регулярно, как другие делали. я не собираюсь еще 3 месяца рефакторингом тестовых заданий заниматся.

**Comment by chmnkh** [comment]
Ну, по пунктам.
Во-первых: проверкой твоего репозитория я на этой неделе занимался несколько раз, поэтому пытаться мне предъявить, что я мало это делаю - глупо и необоснованно.
Во-вторых: не тебе решать, сколько времени я (или кто-либо еще) должен тратить на ревью твоих заданий. То, сколько я (или кто-либо еще) на это могу потратить времени, не в твоих руках вообще. Да и в моих не всегда.
В-третьих: не тебе решать, как и когда я (или кто-либо еще) должен закрывать твои ишью. Если по каким-то причинам ишью не закрыто - значит на это есть причины. Может быть мне так удобнее проверять, может быть одно ишью зависит от другого ишью, может быть я не успел, причин может быть - миллион.
В-четвертых: имей терпение. Я тебя удивлю, но у меня и остальных ребят есть работа, которую нужно выполнять, и есть срочные задания, которые нужно сделать. Думаю ты понимаешь, что посмотреть твое тестовое задание имеет более низкий приоритет, чем фикс какого-нибудь бага перед запуском проекта, например. 
В-пятых: не надо хамить. Говорить что делать и "будь добр" ты можешь своим друзьям, но не здесь. Тебе здесь никто не хамил, так что как насчет впредь общаться нормально?

**Comment by kuvshinova-am** [comment]
1. Хамить ты начал первый.
2. Я умела уже был опыт подобной стажировки и могу рассуждать как это должно работать.
У нас было 40 человек студентов и 3 проверящих, которые кстати тоже работали полный рабочий день, и они успевали проверять всех и оперативно. 
3. А если есть замечания по ишью так пиши их, что бы я могла их исправить.

**Comment by chmnkh** [comment]
По другим пунктам:
2. Это вообще не аргумент. Ты откуда знаешь что происходило у них, и что происходит у нас? И с чего ты взяла, что если тебе "кажется", что тебя медленно проверяют, то это так и есть? А вот у меня тоже есть опыт того, как проверяли меня, других наших ребят до и после меня. И я вижу, что тебя наоборот быстро проверяют, и кто прав? Ты теперь после твоего "опыта стажировки" будешь свои порядки наводить и указывать нам, что тебя плохо проверяют, а ты не много на себя берешь?
3. Повторю в 10 раз: это ишью, как и другое (которое кстати я (внезапно!) закрыл в какой-то момент), в котором ты тоже писала комментарий типа "что с ишью?" я не закрыл _по определенной причине_. Если бы у меня были замечания - я бы их написал. Если их нету - значит их пока нету и ишью не закрыто _по другой причине_.

**Comment by kuvshinova-am** [comment]
я не собираюсь тратить свои нервы на человека для которого нормально так разговаривать, что он даже своего хамства не замечает, так что либо пиши замечания, либо я сама закрою все твои ишью.
