### ISSUE TITLE
Модификаторы БЭМ

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/CV#30]
В блоке skills разберись с модификатором для кружка. 
Для начала определись с тем, [какой у тебя модификатор](https://ru.bem.info/methodology/faq/#%D0%9A%D0%BE%D0%B3%D0%B4%D0%B0-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-%D0%B1%D1%83%D0%BB%D0%B5%D0%B2%D1%8B%D0%B9-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80-%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0--%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80-%D0%BA%D0%BB%D1%8E%D1%87-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5).
Потом его грамотно назови и примени к необходимому элементу. Сейчас у тебя там все сложнее, чем должно и может быть.

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/commit/3811e0436aa81b2b83e351041723a4e2210b9c51
готово

**Comment by kuvshinova-am** [comment]
готово
https://github.com/kuvshinova-am/CV/commit/e393eeb08ad6f431e1013d74714f5a24b953e24d

**Comment by chmnkh** [comment]
А какую ветку смотреть-то в итоге, мастер или рефакторинг?
Ты ошиблась когда в мастер коммитила или так задумано? Если ошиблась, напиши здесь как исправишь)

**Comment by kuvshinova-am** [comment]
master. Меня Geksanit попросил все слить в master поэтому теперь комиты только в этой ветке.

**Comment by chmnkh** [comment]
оу, интересно, нуок

**Comment by kuvshinova-am** [comment]
так что по этому ишью?
