### ISSUE TITLE
list-item из правой колонки

### ISSUE THREAD

**Issue by chmnkh** [kuvshinova-am/CV#31]
Лист-айтемы из education и experience идентичны. Может быть, их следует в отдельный блок вынести?
Тут же обрати внимание на цвет текста и на font-weight. Они у тебя тоже не совсем по макету.

**Comment by kuvshinova-am** [comment]
готово
https://github.com/kuvshinova-am/CV/commit/8a61a2b57556fad499b59a4e6d15d5362215e662
![fireshot capture 6 - cv - http___localhost_9000_](https://user-images.githubusercontent.com/24365265/43202381-90dd0fcc-9045-11e8-9abf-50e1d2beaf4d.png)
p.s. у меня в текстовых блоках используеться другой текст, не тот что в макере, поэтому точное попадание не возможно.

**Comment by ValentinAlexandrovich** [comment]
Модификатор не соответствует БЭМу.

**Comment by kuvshinova-am** [comment]
т.е. нельзя что бы модификатор был цветом?

**Comment by ValentinAlexandrovich** [comment]
А какому типу модификатора ты бы его отнесла?)

**Comment by kuvshinova-am** [comment]
возможно тема, всмысле цвета. 
вот так:
имя-блока__theme_colore, где color передаваемый цвет?

**Comment by ValentinAlexandrovich** [comment]
чем в твоем примере является theme?

**Comment by kuvshinova-am** [comment]
тема оформления

**Comment by ValentinAlexandrovich** [comment]
я про БЭМ методологию

**Comment by kuvshinova-am** [comment]
модификатор, заметила что я вставила лишниее нижнее подчеркивание перед ним.

**Comment by ValentinAlexandrovich** [comment]
Хорошо, тогда theme какая этого модификатора часть?

**Comment by kuvshinova-am** [comment]
что значит какая часть модификатора?

**Comment by ValentinAlexandrovich** [comment]
Почитай вот здесь https://ru.bem.info/methodology/faq/#%D0%9A%D0%BE%D0%B3%D0%B4%D0%B0-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%B2%D0%B0%D1%82%D1%8C-%D0%B1%D1%83%D0%BB%D0%B5%D0%B2%D1%8B%D0%B9-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80-%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0--%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80-%D0%BA%D0%BB%D1%8E%D1%87-%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5 После опиши почему вот этот не соответсвует БЭМ list-item__name_black

**Comment by kuvshinova-am** [comment]
я полагаю что т.к. мне не важно второе значение, то можно сделать булевый модификатор. 
так же list-item__name_black не верен т.к. если используешь ключ-значение, нужно что бы был сам ключ, а не только значение. 
Осталось придумать какое булевое значение придумать для этого элемента.

**Comment by ValentinAlexandrovich** [comment]
Не совсем так, второе значение как раз для тебя важно, поскольку в проекте к примеру может быть несколько цветов, как тогда обходиться булевым значением?)

**Comment by chmnkh** [comment]
До этого ты написала имя-блока__theme_color
Сейчас ты написала имя-блока_theme_black
Тут одно нижнее может весь смысл поменять, поэтому к тебе вопросы возникалию

**Comment by kuvshinova-am** [comment]
ну так я же потом написала про лишнее подчеркивание.
такой вариант подходит?

**Comment by chmnkh** [comment]
Да, в целом подойдет.
Такая вещь еще: делать блок list-item не особо имеет смысла, потому что у тебя по определению лист-айтемы существуют в списке и самостоятельно не могут использоваться, т.к. требуют какого-то объединяющего элемента (как ul для li, например). Тут тебе именно вне контекста списка надо на эту штуку посмотреть и исходя из этого давать название. Про семантические теги так же не забывай, потому что там явный список, а тегов для списка что-то не видно :)

**Comment by kuvshinova-am** [comment]
я сначала сделала списком, а потом у меня возникли проблемы с позиционированием маркера списка, поэтопу пришла к такому варианту. 
так оставить так или всеще на список переделать?
А если переделать, то важно что бы эти маркеры попадали пиксель в пиксель?

**Comment by chmnkh** [comment]
Ну у тебя же сейчас все нормально с маркерами, почему при использовании других элементов что-то не так становится, у тебя же не начинают css правила по другому работать.

**Comment by kuvshinova-am** [comment]
он у меня отказывался позиционироваться.

**Comment by ValentinAlexandrovich** [comment]
После исправления, я  хотел получить от тебя ответ что какой частью модификатора является theme в имя-блока_theme_black, чтобы потом ты сама ответила на свой вопрос ''т.е. нельзя что бы модификатор был цветом?" и  почему list-item__name_black так делать не стоит)

**Comment by kuvshinova-am** [comment]
я сечас могу ответит. theme - ключ, а color(black, blue, и т.д.) это значение. т.е. нельзя использовать только значение без ключа

**Comment by chmnkh** [comment]
> он у меня отказывался позиционироваться.
А что ты пыталась позиционировать, маркер по умолчанию?

**Comment by kuvshinova-am** [comment]
да, потому что что бы сделать маркер подходящего размера я использую font-size для ui но тогда образуються огромные пропуски вокруг, и margin не помогает. Других вариантов как сделать маркер нужного размера я не нашла. Есть вариант с использовать фаил svg но я не хочу к нему прибегать.

**Comment by chmnkh** [comment]
А что изменится когда ты див поменяешь на li, например? CSS будет точно так же работать, просто появятся сверху еще стили для li элемента дефолтные.

**Comment by kuvshinova-am** [comment]
![screenshot from 2018-07-26 16-39-45](https://user-images.githubusercontent.com/24365265/43254934-b116df9a-90f2-11e8-9ada-e8d90e8ae450.png)
![screenshot from 2018-07-26 16-39-52](https://user-images.githubusercontent.com/24365265/43254941-b410d14c-90f2-11e8-95c1-1bbe8aa6bb84.png)

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/pull/32
