### ISSUE TITLE
В контактах должны быть ссылки.

### ISSUE THREAD

**Issue by Geksanit** [kuvshinova-am/CV#5]
Ссылки с соответствующими атрибутами, по стандартам.

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/blob/refactoring/src/page-container/left-block/contact-block/mixins/contact-data.pug

**Comment by Geksanit** [comment]
Не закрывай ишью, раньше времени, мы сами закроем. Почти всё правильно. В ссылке на сайт не хватает атрибутов  `target` `rel`. А что бы было видно на gh-pages, вмержи ветку рефакторинга в мастер.

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/commit/1316367a53f554d51d8f64296f5353d56e0d6d79
дополнила
