### ISSUE TITLE
Все текстовые элементы должны хорошо отображаться с длинным текстом

### ISSUE THREAD

**Issue by Geksanit** [kuvshinova-am/CV#6]
![image](https://user-images.githubusercontent.com/31949379/42828660-fb51ce30-8a12-11e8-9fef-61c22e48e56a.png)

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/commit/e2a56e42f3af131c0ba42d54c2268c4083a9b2c6
готово
