### ISSUE TITLE
добавить .DS_Store в .gitignore

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [kuvshinova-am/CV#8]

**Comment by kuvshinova-am** [comment]
https://github.com/kuvshinova-am/CV/commit/354c1059e1693fa290d828f87dfa1be1d6ab1fc3
исправлено

**Comment by ValentinAlexandrovich** [comment]
Удали их и из репозитория тоже.

**Comment by ValentinAlexandrovich** [comment]
В src так и остались
